### ISSUE TITLE
Issues with deferred  alpine script

### ISSUE THREAD

**Issue by swilla** [victorybiz/laravel-tel-input#2]
I'm using compiled assets and I'm having trouble getting this all to work together. I'm using a base Jetstream application and it already has Alpine setup with webpack. 

If I remove the `defer` from the app.js script tag:
```
        <script src="{{ mix('js/app.js') }}" defer></script>
```

It sort of works, but there are some console errors about AlpineJS not being initialized and some other console errors.

![image](https://user-images.githubusercontent.com/304159/134808552-af336c3e-1fc7-4776-9500-06344a6e4b34.png)

> Alpine Warning: Unable to initialize. Trying to load Alpine before `<body>` is available. Did you forget to add `defer` in Alpine's `<script>` tag?

If we are using compiled assets, should the import statements go before the Apline initialize? 

Here is the `app.js`: 

```
require('./bootstrap');

import Alpine from 'alpinejs';

window.Alpine = Alpine;

import intlTelInput from 'intl-tel-input';
import 'intl-tel-input/build/css/intlTelInput.css';
window.intlTelInput = intlTelInput;

Alpine.start();
```

I've tried including it in the `bootstrap.js` instead, and below `Alpine.start();`.  I can't seem to get this working properly.

**Comment by victorybiz** [comment]
@swilla Please note this package doesn't depend on `Alpinejs`.  
Install the dependency `intl-tel-input` and ensure to place the `@laravelTelInputStyles` in the <head> section of your template before any of your other styles. Place the `@laravelTelInputScripts` directive in your template right before your closing </body> tag and after scripts from libraries like Livewire.

```html
<html>
  <head>
    <!-- ... -->
    @laravelTelInputStyles
    <!-- ... -->
  </head>
<body>
    <!-- content -->

    {{-- app.js --}}
    <script src="{{ asset('js/app.js') }}"></script>

    {{-- Laravel Tel Input --}}
    @laravelTelInputScripts

</body>
</html>
```

Then in `app.js`
```js
require('./bootstrap');

import Alpine from 'alpinejs';
window.Alpine = Alpine;
Alpine.start(); // start Alpine before importing the Intl-tel-input

import intlTelInput from 'intl-tel-input';
window.intlTelInput = intlTelInput;
```
Then in `app.css`
```css
@import 'intl-tel-input/build/css/intlTelInput.css';
```

Then copy the `node_modules/intl-tel-input/build/js/utils.js` to your public directory `public/vendor/intl-tel-input/build/js//utils.js`. If you use Laravel Mix, add the following to your `webpack.mix.js`
```js
mix.copy('node_modules/intl-tel-input/build/js/utils.js', 'public/vendor/intl-tel-input/build/js');
```
