### ISSUE TITLE
On validation error, phone number is repopulated but fails validation on resumit

### ISSUE THREAD

**Issue by mallanza** [victorybiz/laravel-tel-input#25]
When I fill the form, if my validation fails on **another field**, the phone number is repopulated -> so it looks good. 
Nonetheless, when I resubmit the form (with repopulated phone number), now my validation fails on the phone number and it completely resets to blank when the form is shown. 
If I manually change, for example, the last digit, then it works.

```
        <!-- Phone -->
        <div class="mt-4">
            <x-input-label for="companyPhone" :value="__('Company Phone')" />
            <x-tel-input id="companyPhone" name="companyPhone" class="x-tel-input-style w-full block" :value="old('companyPhone')" phone-country-input="#phone_country" autofocus autocomplete="companyPhone" />
            <x-input-error :messages="$errors->get('companyPhone')" class="mt-2" />
        </div>
```

seems that this field is not repopulated on render

`<input type="hidden" id="companyPhone" name="companyPhone" value="" autocomplete="off">`

**Comment by fftfaisal** [comment]
I am having same issue. How do you fixed it ?

**Comment by alaa007** [comment]
Im having same issue
