### ISSUE TITLE
livewire loop

### ISSUE THREAD

**Issue by jbajou** [victorybiz/laravel-tel-input#5]
Hello,

I'm trying to use this package to display a telephone field with country selector in a Livewire component. The input is not shown when loading the page.

I see in the network tab that it keeps firing changes when the phone number is empty, resulting in the loop communication with the Livewire component. It looks like there is a JS event fired like a 'change' for example, resulting in Livewire trying to update the phone number.

Here is how I use it:
```html
<x-tel-input wire:model.lazy="customer.phone" type="text" id="telephone" placeholder="{{ __('+301234567890') }}" name="telephone" />
```

I see that the 'telchange' event is fired a lot of time, even if the filed is not visible yet to the user. With Chrome, it loops for an infinite time. Something updated the customer.phone, Livewire sees a change event (or something like this), uploads it internally, and again and again.

Am I doing something wrong ? Any idea ? No error in JS console.

Thanks

**Comment by jbajou** [comment]
anyone please ?

**Comment by jbajou** [comment]
still no-one ? really ?

**Comment by victorybiz** [comment]
Sorry for the late response, I have been away. 
Can you please share codes from your **component** class and the view blade files as well as errors in your console?

**Comment by jbajou** [comment]
Sure.

```html
@laravelTelInputScripts
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
<script>
    telephone.addEventListener('telchange', function(e) {
        document.getElementById("phone_country").value = e.detail.dialCode;
    });
</script>
```

The blade file:
```html
<label for="telephone" class="...">Phone<span class="font-bold text-red-600">*</span></label>
<x-tel-input wire:ignore  wire:model.lazy="customer.phone" type="text" id="telephone" placeholder="+301234567890" name="telephone" class="..." />
<input wire:model="phone_country" type="hidden" id="phone_country" name="phone_country">
```

Nothing funky in the livewire component class, no event listener or anything like this.

No error in the console, just a crazy amount of network events, looping
![Screenshot 2022-02-08 at 3 29 18 PM](https://user-images.githubusercontent.com/9249644/152996837-d4152785-5ad0-487a-aea5-802ddb289d19.png)

I hope this helps!

**Comment by jbajou** [comment]
it is now clear that this is happening when the field is not visible on page load. We changed our architecture (not related), now the field is visible on page load, and everything works as expected.

**Comment by jbajou** [comment]
So it turns out we just had the issue again and could not live without fixing it.

After investigation, the package doesn't behave well in nested components. I'm PR-ing a fix
