### ISSUE TITLE
How to implement intlTelInput to newly added element?

### ISSUE THREAD

**Issue by vahnmarty** [victorybiz/laravel-tel-input#6]
How to re-initialize `x-tel-input` if it's dynamically added elements.

My frontend code is like this:

```
@foreach($phones as $index => $phone)
      <div class="mb-5" wire:key="phone-{{ $index }}">
                  <label class="form-label">Number<span class="text-danger">*</span></label>
                  <x-tel-input
                      id="phone-{{ $index }}"
                      wire:model="phones.{{ $index }}.number"
                      class="form-control"
                  />
         </div>
@endforeach
``` 

And my backend in Livewire is like this:

```
$this->phones = collect($this->phones)->push([
            'number' => null,
        ]);
```

If I trigger this function, it will add a textbox, but it's not using `intl-tel-input`.

**Comment by victorybiz** [comment]
@vahnmarty Please check the Troubleshooting section of the doc: https://github.com/victorybiz/laravel-tel-input#troubleshooting

Revert if the issue persists or is resolved.

**Comment by vahnmarty** [comment]
> @vahnmarty Please check the Troubleshooting section of the doc: https://github.com/victorybiz/laravel-tel-input#troubleshooting
> 
> Revert if the issue persists or is resolved.

The `$this->dispatchBrowserEvent("telDOMChanged");` fixed it. Thanks.
